// <auto-generated />
using System;
using MediCare.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediCare.Server.Migrations
{
    [DbContext(typeof(MediCareDbContext))]
    [Migration("20251031180315_addRoles")]
    partial class addRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DoctorSpecialization", b =>
                {
                    b.Property<int>("DoctorID")
                        .HasColumnType("integer");

                    b.Property<int>("SpecializationID")
                        .HasColumnType("integer");

                    b.HasKey("DoctorID", "SpecializationID");

                    b.HasIndex("SpecializationID");

                    b.ToTable("DoctorSpecialization");

                    b.HasData(
                        new
                        {
                            DoctorID = 1,
                            SpecializationID = 1
                        },
                        new
                        {
                            DoctorID = 1,
                            SpecializationID = 3
                        },
                        new
                        {
                            DoctorID = 2,
                            SpecializationID = 2
                        },
                        new
                        {
                            DoctorID = 3,
                            SpecializationID = 1
                        },
                        new
                        {
                            DoctorID = 4,
                            SpecializationID = 1
                        },
                        new
                        {
                            DoctorID = 5,
                            SpecializationID = 1
                        });
                });

            modelBuilder.Entity("MediCare.Server.Entities.Doctor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("DoctorDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<TimeOnly>("EndHour")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Facility")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartHour")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DoctorDescription = "Dr. John Smith is an experienced cardiologist and surgeon with over 15 years of practice. He specializes in preventive cardiology, minimally invasive surgery, and patient-centered care.",
                            Email = "john.smith@medicare.com",
                            EndHour = new TimeOnly(16, 0, 0),
                            Facility = "Room 203, MediCare Center",
                            Name = "John",
                            PasswordHash = "AQAAAAIAAYagAAAAENK5qXUBaMBuUFBpttYV0aR626yy171wqlX3Fr6lZ3A63GhTGmRFWptH6uZm1Eu9Og==",
                            PhoneNumber = "123456789",
                            Role = 2,
                            StartHour = new TimeOnly(8, 0, 0),
                            Surname = "Smith"
                        },
                        new
                        {
                            ID = 2,
                            DoctorDescription = "Dr. Emily Johnson is a dedicated neurologist with over 10 years of experience. She focuses on patient-centered care, neurological diagnostics, and innovative treatment methods.",
                            Email = "emily.johnson@medicare.com",
                            EndHour = new TimeOnly(17, 0, 0),
                            Facility = "Building A, Floor 2, MediCare Center",
                            Name = "Emily",
                            PasswordHash = "AQAAAAIAAYagAAAAEK2wr62/vPT1IadjOSNuOLLQ9ECj5CKYZbod4yvHThIexqGnCcp5Yry6PpFG9WRYYw==",
                            PhoneNumber = "987654321",
                            Role = 2,
                            StartHour = new TimeOnly(9, 0, 0),
                            Surname = "Johnson"
                        },
                        new
                        {
                            ID = 3,
                            DoctorDescription = "Dr. Michael Anderson is a skilled cardiologist specializing in arrhythmia management and cardiac imaging diagnostics.",
                            Email = "michael.anderson@medicare.com",
                            EndHour = new TimeOnly(14, 0, 0),
                            Facility = "Room 104, MediCare Center",
                            Name = "Michael",
                            PasswordHash = "AQAAAAIAAYagAAAAEP8zA5dHE7nyVqBLoZwbn3FPUcUJDN4lB3E4uIv9H1sF5xW0+2Fi7vsmzJYgPNh8lA==",
                            PhoneNumber = "555111222",
                            Role = 2,
                            StartHour = new TimeOnly(8, 0, 0),
                            Surname = "Anderson"
                        },
                        new
                        {
                            ID = 4,
                            DoctorDescription = "Dr. Sophia Martinez has extensive experience in non-invasive cardiology and preventive heart health.",
                            Email = "sophia.martinez@medicare.com",
                            EndHour = new TimeOnly(18, 0, 0),
                            Facility = "Room 105, MediCare Center",
                            Name = "Sophia",
                            PasswordHash = "AQAAAAIAAYagAAAAEPxZkz/F7fYxzUVEXn9xIQKo5Tk1DbiRdnXx7SC7pPjUJW1xVdYzqk5GfYjxyK6K+w==",
                            PhoneNumber = "555333444",
                            Role = 2,
                            StartHour = new TimeOnly(10, 0, 0),
                            Surname = "Martinez"
                        },
                        new
                        {
                            ID = 5,
                            DoctorDescription = "Dr. David Kowalski is a cardiologist focused on hypertension treatment, cardiac stress testing, and patient education.",
                            Email = "david.kowalski@medicare.com",
                            EndHour = new TimeOnly(15, 30, 0),
                            Facility = "Room 101, MediCare Center",
                            Name = "David",
                            PasswordHash = "AQAAAAIAAYagAAAAEKh2N3ZC1HkP7HhKJ7blQ7tb4jHY0mM3PwOydZx5Lq3yW6SkmtFfw4tq1LZzW9zENg==",
                            PhoneNumber = "555666777",
                            Role = 2,
                            StartHour = new TimeOnly(7, 30, 0),
                            Surname = "Kowalski"
                        },
                        new
                        {
                            ID = 7,
                            DoctorDescription = "Dr. Evan Chris is a cardiologist focused on hypertension treatment, cardiac stress testing, and patient education.",
                            Email = "Evan.chris@medicare.com",
                            EndHour = new TimeOnly(15, 30, 0),
                            Facility = "Room 101, MediCare Center",
                            Name = "Evan",
                            PasswordHash = "AQAAAAIAAYagAAAAEKh2N3ZC1HkP7HhKJ7blQ7tb4jHY0mM3PwOydZx5Lq3yW6SkmtFfw4tq1LZzW9zENg==",
                            PhoneNumber = "888888888",
                            Role = 3,
                            StartHour = new TimeOnly(7, 30, 0),
                            Surname = "Chris"
                        });
                });

            modelBuilder.Entity("MediCare.Server.Entities.NewsItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.ToTable("NewsItems");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Join us for a free blood pressure check and consultation with our cardiology team.",
                            ImageURL = "https://i.ibb.co/k2hBfcpL/blood-pressure.jpg",
                            Title = "Free Blood Pressure Screening"
                        },
                        new
                        {
                            ID = 2,
                            Date = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Get your flu shot before the season starts. No appointment needed.",
                            ImageURL = "https://i.ibb.co/BHxNtvLj/vaccination.jpg",
                            Title = "Flu Vaccination Campaign"
                        },
                        new
                        {
                            ID = 3,
                            Date = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learn how to prepare balanced meals with our nutritionist. Free entry.",
                            ImageURL = "https://i.ibb.co/HTVch19N/healthy-eating.jpg",
                            Title = "Healthy Eating Workshop"
                        },
                        new
                        {
                            ID = 4,
                            Date = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Educational lectures and free glucose testing for all visitors.",
                            ImageURL = "https://i.ibb.co/1VTGg5c/diabetes.jpg",
                            Title = "World Diabetes Day Awareness"
                        });
                });

            modelBuilder.Entity("MediCare.Server.Entities.Patient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PESEL")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Birthday = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.brown@example.com",
                            Name = "Michael",
                            PESEL = "90010112345",
                            PasswordHash = "AQAAAAIAAYagAAAAELg5sSlJ9Z8pG1rKefpy1Pbfql3D+S2J7bXiM77uUOfyfdvsBcOdh75oC42ktQ8h3w==",
                            PhoneNumber = "555111222",
                            Role = 1,
                            Status = 1,
                            Surname = "Brown"
                        },
                        new
                        {
                            ID = 2,
                            Birthday = new DateTime(1985, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.williams@example.com",
                            Name = "Sarah",
                            PESEL = "85050567890",
                            PasswordHash = "AQAAAAIAAYagAAAAELo4ftbkWmWkCzg4YbZhATzJFIRg6s7HBY322tgk4mquh9bHdQy3NraDhJLvnhjJEQ==",
                            PhoneNumber = "555333444",
                            Role = 1,
                            Status = 1,
                            Surname = "Williams"
                        },
                        new
                        {
                            ID = 3,
                            Birthday = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna.kowalska@example.com",
                            Name = "Anna",
                            PESEL = "80010112345",
                            PasswordHash = "...",
                            PhoneNumber = "555777888",
                            Role = 1,
                            Status = 1,
                            Surname = "Kowalska"
                        },
                        new
                        {
                            ID = 4,
                            Birthday = new DateTime(1975, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "piotr.nowak@example.com",
                            Name = "Piotr",
                            PESEL = "75050567890",
                            PasswordHash = "...",
                            PhoneNumber = "555999000",
                            Role = 1,
                            Status = 1,
                            Surname = "Nowak"
                        });
                });

            modelBuilder.Entity("MediCare.Server.Entities.RefreshToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("DoctorID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<int?>("PatientID")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("DoctorID")
                        .IsUnique();

                    b.HasIndex("PatientID")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MediCare.Server.Entities.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("RoomNumber")
                        .HasColumnType("integer");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            RoomNumber = 101,
                            RoomType = "Cardiology Consultation Room"
                        },
                        new
                        {
                            ID = 2,
                            RoomNumber = 102,
                            RoomType = "Orthopedic Consultation Room"
                        },
                        new
                        {
                            ID = 3,
                            RoomNumber = 103,
                            RoomType = "Dermatology Consultation Room"
                        },
                        new
                        {
                            ID = 5,
                            RoomNumber = 104,
                            RoomType = "Cardiology Consultation Room"
                        },
                        new
                        {
                            ID = 6,
                            RoomNumber = 106,
                            RoomType = "Orthopedic Consultation Room"
                        },
                        new
                        {
                            ID = 8,
                            RoomNumber = 107,
                            RoomType = "Dermatology Consultation Room"
                        });
                });

            modelBuilder.Entity("MediCare.Server.Entities.Specialization", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("SpecializationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecializationHighlight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecializationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            SpecializationDescription = "Specialist in heart diseases",
                            SpecializationHighlight = "Protect your heart with expert cardiovascular care and diagnostics.",
                            SpecializationName = "Cardiologist"
                        },
                        new
                        {
                            ID = 2,
                            SpecializationDescription = "Specialist in musculoskeletal system injuries and disorders",
                            SpecializationHighlight = "Restore mobility and strength with advanced orthopedic solutions",
                            SpecializationName = "Orthopedic Surgeon"
                        },
                        new
                        {
                            ID = 3,
                            SpecializationDescription = "Specialist in skin conditions",
                            SpecializationHighlight = "Healthy skin starts here comprehensive dermatological treatments for all ages.",
                            SpecializationName = "Dermatologist"
                        });
                });

            modelBuilder.Entity("MediCare.Server.Entities.Visit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("text");

                    b.Property<int>("DoctorID")
                        .HasColumnType("integer");

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.Property<string>("PrescriptionText")
                        .HasColumnType("text");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<int>("RoomID")
                        .HasColumnType("integer");

                    b.Property<int>("SpecializationID")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.Property<string>("VisitNotes")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("VisitTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("ID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.HasIndex("RoomID");

                    b.HasIndex("SpecializationID");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AdditionalNotes = "Please discuss the test results in advance.",
                            DoctorID = 1,
                            PatientID = 1,
                            Reason = 1,
                            RoomID = 1,
                            SpecializationID = 1,
                            Status = 1,
                            VisitDate = new DateOnly(2025, 10, 20),
                            VisitTime = new TimeOnly(10, 30, 0)
                        },
                        new
                        {
                            ID = 2,
                            DoctorID = 2,
                            PatientID = 2,
                            Reason = 3,
                            RoomID = 2,
                            SpecializationID = 2,
                            Status = 1,
                            VisitDate = new DateOnly(2025, 10, 21),
                            VisitTime = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            ID = 3,
                            AdditionalNotes = "Checkup after previous visit.",
                            DoctorID = 1,
                            PatientID = 2,
                            PrescriptionText = "Vitamin D 2000 IU daily for 3 months",
                            Reason = 2,
                            RoomID = 1,
                            SpecializationID = 1,
                            Status = 2,
                            VisitDate = new DateOnly(2025, 10, 22),
                            VisitNotes = "Patient recovering well, continue current treatment.",
                            VisitTime = new TimeOnly(9, 30, 0)
                        },
                        new
                        {
                            ID = 4,
                            AdditionalNotes = "Routine annual checkup.",
                            DoctorID = 3,
                            PatientID = 3,
                            Reason = 4,
                            RoomID = 3,
                            SpecializationID = 3,
                            Status = 2,
                            VisitDate = new DateOnly(2025, 10, 25),
                            VisitNotes = "All vitals normal, recommend regular exercise.",
                            VisitTime = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            ID = 5,
                            AdditionalNotes = "Patient complains of recurring headaches.",
                            DoctorID = 2,
                            PatientID = 4,
                            Reason = 1,
                            RoomID = 2,
                            SpecializationID = 2,
                            Status = 1,
                            VisitDate = new DateOnly(2025, 10, 27),
                            VisitTime = new TimeOnly(15, 0, 0)
                        });
                });

            modelBuilder.Entity("SpecializationRoom", b =>
                {
                    b.Property<int>("SpecializationID")
                        .HasColumnType("integer");

                    b.Property<int>("RoomID")
                        .HasColumnType("integer");

                    b.HasKey("SpecializationID", "RoomID");

                    b.HasIndex("RoomID");

                    b.ToTable("SpecializationRooms");

                    b.HasData(
                        new
                        {
                            SpecializationID = 1,
                            RoomID = 1
                        },
                        new
                        {
                            SpecializationID = 1,
                            RoomID = 5
                        },
                        new
                        {
                            SpecializationID = 2,
                            RoomID = 2
                        },
                        new
                        {
                            SpecializationID = 2,
                            RoomID = 6
                        },
                        new
                        {
                            SpecializationID = 3,
                            RoomID = 3
                        },
                        new
                        {
                            SpecializationID = 3,
                            RoomID = 8
                        });
                });

            modelBuilder.Entity("DoctorSpecialization", b =>
                {
                    b.HasOne("MediCare.Server.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCare.Server.Entities.Specialization", null)
                        .WithMany()
                        .HasForeignKey("SpecializationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediCare.Server.Entities.RefreshToken", b =>
                {
                    b.HasOne("MediCare.Server.Entities.Doctor", "Doctor")
                        .WithOne("RefreshToken")
                        .HasForeignKey("MediCare.Server.Entities.RefreshToken", "DoctorID");

                    b.HasOne("MediCare.Server.Entities.Patient", "Patient")
                        .WithOne("RefreshToken")
                        .HasForeignKey("MediCare.Server.Entities.RefreshToken", "PatientID");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediCare.Server.Entities.Visit", b =>
                {
                    b.HasOne("MediCare.Server.Entities.Doctor", "Doctor")
                        .WithMany("Visits")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCare.Server.Entities.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCare.Server.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCare.Server.Entities.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Room");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("SpecializationRoom", b =>
                {
                    b.HasOne("MediCare.Server.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCare.Server.Entities.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("MediCare.Server.Entities.Doctor", b =>
                {
                    b.Navigation("RefreshToken")
                        .IsRequired();

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("MediCare.Server.Entities.Patient", b =>
                {
                    b.Navigation("RefreshToken")
                        .IsRequired();

                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
