// <auto-generated />
using System;
using MediCare.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediCare.Server.Migrations
{
    [DbContext(typeof(MediCareDbContext))]
    partial class MediCareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DoctorSpecialization", b =>
                {
                    b.Property<int>("DoctorID")
                        .HasColumnType("integer");

                    b.Property<int>("SpecializationID")
                        .HasColumnType("integer");

                    b.HasKey("DoctorID", "SpecializationID");

                    b.HasIndex("SpecializationID");

                    b.ToTable("DoctorSpecialization");

                    b.HasData(
                        new
                        {
                            DoctorID = 1,
                            SpecializationID = 1
                        },
                        new
                        {
                            DoctorID = 1,
                            SpecializationID = 3
                        },
                        new
                        {
                            DoctorID = 2,
                            SpecializationID = 2
                        });
                });

            modelBuilder.Entity("MediCare.Server.Entities.Doctor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<TimeOnly>("EndHour")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<TimeOnly>("StartHour")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "john.smith@medicare.com",
                            EndHour = new TimeOnly(16, 0, 0),
                            Name = "John",
                            PasswordHash = "AQAAAAIAAYagAAAAENK5qXUBaMBuUFBpttYV0aR626yy171wqlX3Fr6lZ3A63GhTGmRFWptH6uZm1Eu9Og==",
                            PhoneNumber = "123456789",
                            StartHour = new TimeOnly(8, 0, 0),
                            Surname = "Smith"
                        },
                        new
                        {
                            ID = 2,
                            Email = "emily.johnson@medicare.com",
                            EndHour = new TimeOnly(17, 0, 0),
                            Name = "Emily",
                            PasswordHash = "AQAAAAIAAYagAAAAEK2wr62/vPT1IadjOSNuOLLQ9ECj5CKYZbod4yvHThIexqGnCcp5Yry6PpFG9WRYYw==",
                            PhoneNumber = "987654321",
                            StartHour = new TimeOnly(9, 0, 0),
                            Surname = "Johnson"
                        });
                });

            modelBuilder.Entity("MediCare.Server.Entities.Patient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PESEL")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Birthday = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.brown@example.com",
                            Name = "Michael",
                            PESEL = "90010112345",
                            PasswordHash = "AQAAAAIAAYagAAAAELg5sSlJ9Z8pG1rKefpy1Pbfql3D+S2J7bXiM77uUOfyfdvsBcOdh75oC42ktQ8h3w==",
                            PhoneNumber = "555111222",
                            Surname = "Brown"
                        },
                        new
                        {
                            ID = 2,
                            Birthday = new DateTime(1985, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.williams@example.com",
                            Name = "Sarah",
                            PESEL = "85050567890",
                            PasswordHash = "AQAAAAIAAYagAAAAELo4ftbkWmWkCzg4YbZhATzJFIRg6s7HBY322tgk4mquh9bHdQy3NraDhJLvnhjJEQ==",
                            PhoneNumber = "555333444",
                            Surname = "Williams"
                        });
                });

            modelBuilder.Entity("MediCare.Server.Entities.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("Availability")
                        .HasColumnType("boolean");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("integer");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Availability = true,
                            RoomNumber = 101,
                            RoomType = "Consultation Room"
                        },
                        new
                        {
                            ID = 2,
                            Availability = true,
                            RoomNumber = 102,
                            RoomType = "Consultation Room"
                        },
                        new
                        {
                            ID = 3,
                            Availability = false,
                            RoomNumber = 201,
                            RoomType = "Operating Room"
                        });
                });

            modelBuilder.Entity("MediCare.Server.Entities.Specialization", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("SpecializationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecializationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            SpecializationDescription = "Specialist in heart diseases",
                            SpecializationName = "Cardiologist"
                        },
                        new
                        {
                            ID = 2,
                            SpecializationDescription = "Specialist in musculoskeletal system injuries and disorders",
                            SpecializationName = "Orthopedic Surgeon"
                        },
                        new
                        {
                            ID = 3,
                            SpecializationDescription = "Specialist in skin conditions",
                            SpecializationName = "Dermatologist"
                        });
                });

            modelBuilder.Entity("MediCare.Server.Entities.Visit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("DoctorID")
                        .HasColumnType("integer");

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.Property<int>("RoomID")
                        .HasColumnType("integer");

                    b.Property<int>("StatusID")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.HasIndex("RoomID");

                    b.HasIndex("StatusID");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("MediCare.Server.Entities.VisitStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ID");

                    b.ToTable("VisitStatuses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Scheduled"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Completed"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("DoctorSpecialization", b =>
                {
                    b.HasOne("MediCare.Server.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCare.Server.Entities.Specialization", null)
                        .WithMany()
                        .HasForeignKey("SpecializationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediCare.Server.Entities.Visit", b =>
                {
                    b.HasOne("MediCare.Server.Entities.Doctor", "Doctor")
                        .WithMany("Visits")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCare.Server.Entities.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCare.Server.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCare.Server.Entities.VisitStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Room");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MediCare.Server.Entities.Doctor", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("MediCare.Server.Entities.Patient", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
